### PR TITLE
Make sundrio model stateless and idempotent

### PR DESCRIPTION
**Pull request by iocanel**
The goal of this pull request to make the sundrio model (`io.sundr.codegen.model`) stateless and idempotent.

### Background
Up until know model classes where using an repository that held all know type definitions (called `DefinitionRepository`).
Methods that we using this repo include:
- equals()
- hashCode()
- toString()

The undesirable side effect was that changing the content of the repository could alter the behavior of those classes, even when the internal state of the class remained the same. 

This is a code smell, that introduces a level of uncertainty in the sundrio API.

### Changes

- Introduce `render()` to replace `toString()` for code generation purposes.
- ClassRef and TypeDef model classes use no state:
    -  `ClassRef.getDefinition()` replaced by `GetDefinition.of()`
    - `TypeRef.isAssignable(TypeRef other)` replaced by `Assignable.isAssignable(TypeRef ref).from(TypeRef other)`
    - `TypeDef.isAssignable(TypeDef other)` replaced by `Assignable.isAssignable(TypeDef ref).from(TypeDef other)`
- ClassRef now uses an idempotent version of `getName()` and `getPackageName()`

### Related issues
Resolves: #212 #213
Related: #216 (It is not technically possible to proceed with 216, a followup pull request will deal with that).

### CODE REVIEW

**Review by geoand — APPROVED** [review]
I'm not the best person to judge this, but it sounds reasonable to me

**Comment by metacosm** [comment]
Should we aim to use this change in the client's next release?

**Comment by iocanel** [comment]
> Should we aim to use this change in the client's next release?

I feel that this change would add to stability of the pojo generator, since its now idempotency is guaranteed.

**Comment by metacosm** [comment]
I tend to agree. What do you think @manusa, @rohanKanojia ?

**Comment by manusa** [comment]
I like idempotent, stateless and reproducible. 
I don't know what the implications of this are for the client. i.e. Is this going to alter the generated code API in some way (disappearing methods)? or just the content of the methods? (Sorry for the maybe naive question)

**Comment by iocanel** [comment]
> I like idempotent, stateless and reproducible.
> I don't know what the implications of this are for the client. i.e. Is this going to alter the generated code API in some way (disappearing methods)? or just the content of the methods? (Sorry for the maybe naive question)

The client generated code is not expected to change. The crd generator will have to align though due to the removal of `ClassRef.getDefinition()`. This is no biggie, I've aligned things locally and its trivial.

**Comment by iocanel** [comment]
Not sure what exactly happened but the commits got lost after I rebased from the master

**Comment by iocanel** [comment]
Created a new pull request that is a superset of this: https://github.com/sundrio/sundrio/pull/219

**Pull request closed without merging**
