### PR TITLE
task: making the baseline java 11

### PR DESCRIPTION
**Pull request by shawkins**
closes: #466

Added an enforcer that the java version must be 11+  - that can be removed if it doesn't seem necessary.

maven-plugin-plugin needed to be updated as well, so I did a little alignment / update of the maven related dependencies - but didn't try to push it all the way to the latest.

removed any overrides that didn't seem to be needed given that they are coming from the parent.

had to add some compiler args to directly reference the com.sun stuff in the dsl test.

### CODE REVIEW

**Review by andreaTP — APPROVED** [review]
Lgtm! Thanks for taking this!

Have we decided to drop Java 8 support from the Kubernetes client too?

Otherwise we are going to be stuck on sundrio version ...

**Comment by shawkins** [comment]
> Have we decided to drop Java 8 support from the Kubernetes client too?

Sounds good to me. 

I haven't tested, but I'm pretty sure you could keep using this java 11 version of sundrio to perform a java 8 compatible build of fabric8 as long as you are using a later jdk to perform the build.

**Comment by andreaTP** [comment]
Let's discuss this tomorrow :+1:

**Review by iocanel — COMMENTED** [review]
My understanding was that kubernetes-client would drop support for java 8 too.
If not this might be risky as @andreaTP already mentioned.

Also, I will need to check what the official client is doing in that regard cause I wouldn't want to cause break them either.

So, I will change my review till we short these out.

**Comment by iocanel** [comment]
Ok, seems that the official client is already on java 11, so we just have to align with fabric8

**Comment by andreaTP** [comment]
> Ok, seems that the official client is already on java 11, so we just have to align with fabric8

I cannot confirm, unfortunately:

https://github.com/fabric8io/kubernetes-client/blob/0c80a66d10bf7096864246ce453413e0da4edbd2/.github/workflows/release.yaml#L64

**Comment by shawkins** [comment]
> I cannot confirm, unfortunately:

@andreaTP he's referring to https://github.com/kubernetes-client/java which does default to java 11 in their pom.

**Comment by shawkins** [comment]
@andreaTP @iocanel the only other consideration here is if we do expect java 8 runtime support for the sundrio annotations / api.builder - the source / target can be set there to stay at java 8 if needed.

**Comment by iocanel** [comment]
> @andreaTP @iocanel the only other consideration here is if we do expect java 8 runtime support for the sundrio annotations / api.builder - the source / target can be set there to stay at java 8 if needed.

What do you mean?

**Comment by shawkins** [comment]
> What do you mean?

Those are the only parts of sundrio that should be used at runtime and could remain 8 compatible if needed.

**Comment by iocanel** [comment]
> > What do you mean?
> 
> Those are the only parts of sundrio that should be used at runtime and could remain 8 compatible if needed.

That's a good point, but how would a project that is build with java 8. would be able to use our annotation processors that require java 11?

**Comment by shawkins** [comment]
> That's a good point, but how would a project that is build with java 8. would be able to use our annotation processors that require java 11?

It's the same as what I'm mentioning for fabric8 - as long as you build with a 11+ jdk, you can still target 8 compatibility.

**Comment by manusa** [comment]
The agreement for Fabric8 Kubernetes Client is to set the baseline to Java 11 on our next major (v7).
The initial plan is to do a last minor release (either v6.12 or v6.13) and then set the main branch SNAPSHOT version to v7 and start working on it.

**Review by andreaTP — APPROVED** [review]
Agreed 👍 thanks for the patience @shawkins

**Comment by shawkins** [comment]
I tried to also set maven.compiler.release to 11, but it complains that you can't do that and use the compiler exports.

**Comment by shawkins** [comment]
@iocanel we should be ready to commit this with your approval

**Pull request merged**
