### PR TITLE
fix: Handle consistnently name diffs when there are name clashes.

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by iocanel** [comment]
@metacosm: can you please let me know if this fixes the issue for you?

**Comment by metacosm** [comment]
Yep, going to give a try now. Is it normal that CI fails, though?

**Comment by iocanel** [comment]
@metacosm: Ooops didn't realize that. Let me fix that and you can try later.

**Comment by metacosm** [comment]
It indeed doesn't build locally either…

**Pull request closed without merging**
