### PR TITLE
[#129]: Fix invalid code, generated when running with Java 11

### PR DESCRIPTION
**Pull request by ctron**

### CODE REVIEW

**Comment by iocanel** [comment]
@ctron: being a complete java 11 noob here. What exactly is that change that triggeres this issue? I looked at the java docs for java.reflect.Methos but they weren't that helpful.

**Comment by ctron** [comment]
The problem was already there, as the lookup code, which looks for constructors is can call, doesn't take package level visibility under consideration. So you can run into this issue on Java 8 already.

However it seems that something in Java 11 has changed, and I don't know what exactly, but it reproducibly creates a reference to `AbstractStringBuilder`, which is wrong:

~~~
public A withNewName(AbstractStringBuilder arg1,Void arg2)
public A withNewName(String arg1)
public A withNewName(StringBuilder arg1)
public A withNewName(StringBuffer arg1)
~~~

The issue is fixed in any case if the filter checks for the constructor being either public or protected, which filters out private and "default" (package level).

**Comment by iocanel** [comment]
@ctron: Thanks!

I'll merge it and try to have a release out later today!

**Comment by iocanel** [comment]
@ctron: Release 0.16.4.

**Comment by ctron** [comment]
> @ctron: Released 0.16.4.
Thanks!

**Pull request merged**
