### PR TITLE
fix: upgrade mvn / mvnw support to 3.9

### PR DESCRIPTION
**Pull request by shawkins**
closes: #457

### CODE REVIEW

**Comment by shawkins** [comment]
cc @rohanKanojia

**Comment by rohanKanojia** [comment]
@shawkins : Thanks a lot for your fix! I tested it on JDK11 + JDK17 and I don't see the error anymore. I also reviewed the changes, apart from plugin version upgrades most changes are for removing trailing whitespace (probably added via plugin).

However, I'm not able to build project on JDK8 . I think there is some configuration mistake on my side. I'm getting this error when compiling on JDK8:
```
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.23.0:format (default) on project sundr-pom: Execution default of goal net.revelc.code.formatter:formatter-maven-plugin:2.23.0:format failed: Unable to load the mojo 'format' in the plugin 'net.revelc.code.formatter:formatter-maven-plugin:2.23.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: net/revelc/code/formatter/FormatterMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>net.revelc.code.formatter:formatter-maven-plugin:2.23.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy

```

**Comment by shawkins** [comment]
@rohanKanojia I think what is happening is that formatting is turned off for ci runs, so we don't see a problem there with java 8. Do you think we should try to make formatting still work with java 8?

**Comment by rohanKanojia** [comment]
> Do you think we should try to make formatting still work with java 8?

@shawkins : In my opinion, it's not that important.

**Review by iocanel — APPROVED** [review]
LGTM

**Pull request merged**
