### PR TITLE
fix #263 merging fluent / fluentimpl

### LINKED ISSUE #263: Eliminate Fluent interface
Historically, we separated the `Builder` from the `Fluent`/`FluentImpl` in order to supportthe `Inline` concept: `Being able to use the fluent part of a builder, but with having a different method in the end instead of build. An example of how it was used in the `kubernetes-client`:

```java
Pod pod = client.pods().createNew()
   .withNewSpec()
      .withName("my-pod")
  .endSpec()
  // more code
  .done();
```

It seems though that we don't need both a `Fluent` interface and a `FluentImpl` class.
It might make sense if we collapsed them into one class that will be called `Fluent`.

`Builder` heavy libraries and frameworks could be greatly benefited by the reduced size and the simplified signatures.

### PR DESCRIPTION
**Pull request by shawkins**
Hopefully this is still valid.

There is a usage of the fluent interface/impl in fabric8 that can be easily changed to just the concrete fluent.

cc @iocanel @manusa

### CODE REVIEW

**Comment by iocanel** [comment]
@shawkins: Thank you for putting time on this. This is a far from trivial task. In the past I tried myself and gave up. 

If I remember correctly the major pain point for me was what to do with intrefaces annotated with `@Buildable` as ATM we do generate a `Fluent` that is implemented by Builders of classes implementing the original interface.

Eitherway, before we merge this. I need to ensure that all downstream projects work. So, it will take some time.

**Comment by shawkins** [comment]
@iocanel would it be possible to include additional test cases for the things that may be problematic?

I tried with a buildable interface and that caused the pojo to be generated as well.  From there the fluent and builder looked as expected.

With an abstract buildable I see only the fluent being generated.  Just like the change needed in fabric8, downstream projects would no longer use the fluent interface and just extend the concrete fluent.

**Comment by iocanel** [comment]
> @iocanel would it be possible to include additional test cases for the things that may be problematic?

I think that the `shapes` example should cover most of cases.

> I tried with a buildable interface and that caused the pojo to be generated as well. From there the fluent and builder looked as expected.

Before adding support for `Pojo` generation when interfaces where annotated a `Fluent` was generated.
Implementing types had their Fluent extend the interface Fluent (or so I think). This seems to be broken now anyways and most probably this isn't even used.

I do see some failures in the downstream check which are due to explict references on the Impl class.
Can you please address that downstream so that we can re-run the check.

**Comment by shawkins** [comment]
> Can you please address that downstream so that we can re-run the check.

Won't I need at least a snapshot release of sundrio before I can do that?

**Comment by shawkins** [comment]
@iocanel how do you want to proceed on this?

**Comment by iocanel** [comment]
> > Can you please address that downstream so that we can re-run the check.
> 
> Won't I need at least a snapshot release of sundrio before I can do that?

I think that you might be able to fix that without a new release just by changing from FluentImpl to Fluent.

**Comment by shawkins** [comment]
> I think that you might be able to fix that without a new release just by changing from FluentImpl to Fluent.

How would that work given that Fluent with existing releases of sundrio will be an interface?  

I'll just wait for the new release and update then.

**Comment by iocanel** [comment]
> How would that work given that Fluent with existing releases of sundrio will be an interface?
> 

Well, unless you explicitly implment the `Fluent` I don't see why that is a problem.

**Comment by shawkins** [comment]
State before this pr:

fabric8 has RunConfigNestedImpl extends RunConfigFluentImpl<RunConfigNested> implements RunConfigNested - https://github.com/fabric8io/kubernetes-client/blob/5fb4ea82dfe55932a10b646fecde7812b0a28ef0/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/run/RunOperations.java#L31

After this pr, RunConfigFluentImpl will no longer exist.  The fabric8 code will to instead become:

RunConfigNested extends RunConfigFluent<RunConfigNested>

I cannot make that change ahead of time as RunConfigFluent is an interface.

**Comment by iocanel** [comment]
Ok, I am creating a 0.95.0 release with all the other changes that have recently made it in.
Then I'll branch and we can go for 0.100.0.

**Comment by shawkins** [comment]
> Then I'll branch and we can go for 0.100.0.

Sounds good.  Will there be snapshot builds available to update the downstream against?

There are some additional changes that may be good before the final 0.100.0 release.  Please see https://github.com/sundrio/sundrio/pull/379/commits/6168288168615b5bdf691dc4b25e842aa878e6dc

**Comment by iocanel** [comment]
> Sounds good. Will there be snapshot builds available to update the downstream against?

I haven't configured snapshot releases. Will work on that.

**Review by iocanel — APPROVED** [review]
LGTM

**Pull request merged**
